##### setup report #####
configfile: "config/config.json"


##### load rules #####


include: "rules/apply_models.smk"
include: "rules/in_silico_mixture.smk"

##### target rules #####


rule all:
    input:
        expand("results/{name}_alpha_estimates.tsv", name=config["name"]),


